@startuml
left to right direction
:User: as User
User --> (Få kvittering)
User --> (Logg inn)
(Logg inn) --> (Redigere brukerinformasjon)
User --> (Verifisert konto)
(Verifisert konto) --> (Oprette guide)
(Oprette guide) --> (Redigere)
(Redigere) --> (Legge ut)
(Legge ut) --> (Oversikt over påmelding)
User --> (Se på tilgjengelige turer)
(Se på tilgjengelige turer) --> (Påmelding)
(Påmelding) --> (Oversikt over bestiling)
(Oversikt over bestiling) --> (Betaling)
(Betaling) --> (Card, Paypal, bankterminal)
(Betaling) --> (Mobilapplikasjon)

@enduml

