@startuml
'https://plantuml.com/use-case-diagram

:Administratrator: as Admin
:Bruker:  as Bruker

(Start) --> (Admin)
(Start) --> (Bruker)

(Admin) --> (Opprette guide)
(Opprette guide) --> (Redigere)
(Redigere) --> (Legge ut)
(Legge ut) --> (Lagre)
(Lagre) --> (Oversikt over innmelding)

(Bruker) --> (Se på tilgjenngelige turer)
(Se på tilgjenngelige turer) --> (Påmelding)
(Påmelding) --> (Oversikt over innmelding)
(Påmelding) --> (Oversikt over bestillinger)


@enduml

