@startuml
left to right direction
:User: as User
:Administrator: as Admin
Admin --> (Logg inn)
User --> (Logg inn)
Admin --> (Administrere guider)
(Administrere guider) --> (Verifisere brukerkonto)
Admin --> (Håndtere brutt på rettningslinjer)
Admin --> (Administrere  innhold)
(Administrere  innhold) --> (Oppdatere status)



Admin --> (Statestikk)
(Statestikk) --> (Oversikt over brukeraktivitet)

Admin --> (Håndtere henvendelser)
User --> (Verifisert konto)

Admin --> (Administrere brukerkontoer)
User --> (Lage en User brukerkonto)
User --> (Få kvittering)
(Logg inn) --> (Redigere brukerinformasjon)
(Verifisert konto) --> (Oprette guide)
(Oprette guide) --> (Redigere)
(Redigere) --> (Legge ut)
(Legge ut) --> (Oversikt over påmelding)
User --> (Se på tilgjengelige turer)
(Se på tilgjengelige turer) --> (Påmelding)
(Påmelding) --> (Oversikt over bestiling)
(Oversikt over bestiling) --> (Betaling)
(Betaling) --> (Card, Paypal, bankterminal)
(Betaling) --> (Mobilapplikasjon)

@enduml

